# Generated by Django 2.2.6 on 2019-11-13 18:45

import bidding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='endTime',
            field=models.DateTimeField(default=bidding.models.default_end_time),
        ),
    ]
