# Generated by Django 2.2.7 on 2019-11-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0005_auto_20191116_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(upload_to='media/items'),
        ),
    ]
