# Generated by Django 2.2.7 on 2019-11-21 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0006_auto_20191121_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bid_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidding.Bid'),
        ),
    ]
