# Generated by Django 2.2.7 on 2019-11-21 17:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0008_auto_20191121_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=12),
        ),
    ]
