# Generated by Django 2.2.7 on 2019-11-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0009_auto_20191121_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bid_price',
        ),
        migrations.AddField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidding.Item'),
        ),
    ]
