# Generated by Django 2.2.7 on 2019-11-26 23:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0010_auto_20191123_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ended_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=21),
        ),
    ]
